common/urls.py
from django.urls import path
from . import views

app_name = 'common'
urlpatterns = [
    path('projecthome', views.project_home, name='projecthome'),
    path('customerlogin', views.customer_login, name='customerlogin'),
    path('sellerlogin', views.seller_login, name='sellerlogin'),
    path('customer_reg', views.customer_registration, name='customer_reg'),
    path('seller_reg', views.seller_registration, name='seller_reg'),                                                                       
    path('email_exist', views.email_exist, name='email_exist'),                                                       
]

customer/urls.py
from django.urls import path
from . import views
app_name= 'customer'
urlpatterns=[
    path('customerhome', views.customer_home, name='customerhome'),
    path('changePassword', views.change_password, name='changePassword'),
    path('productDetails/<int:pid>', views.prod_details, name='productDetails'),
    path('cart', views.customer_cart, name='cart'),
    path('orders', views.customer_orders, name='orders'),
    path('profile', views.profile, name='profile'),
    path('remove_cart/<int:pid>', views.remove_item_from_cart, name='remove_cart'),
    path('logout', views.logout, name='logout'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('common/', include('common.urls')),
    path('customer/', include('customer.urls')),
    path('ecom_admin/', include('ecom_admin.urls')),
    path('seller/', include('seller.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

customer/models.py
from django.db import models
from seller.models import Product
from common.models import Customer

# Create your models here.
class Cart(models.Model):
    product_details = models.ForeignKey(Product, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)

customer/views.py
from django.shortcuts import render,redirect
from seller.models import Product
from common.models import Customer
from customer.models import Cart
from .auth_guard import auth_customer


# Create your views here.
@auth_customer
def customer_home(request):
    product_list = Product.objects.all() # all() is used to get every sellers products from the database.
    return render(request, 'customer/customer_home.html',{'products':product_list})

@auth_customer
def change_password(request):
    msg = ''
    if request.method == 'POST':
        customer = Customer.objects.get(id = request.session['customer'])

        customer_password = request.POST['current_password']
        new_pass = request.POST['new_password']
        confirm_pass = request.POST['confirm_password']

        if customer.customer_password == customer_password:

            if new_pass == confirm_pass:
                customer.customer_password = new_pass
                customer.save()
                msg = 'Password changed successfully'
            else:
                msg = 'Password Does not Match'
        else:
            msg = 'Incorrect password'
    return render(request, 'customer/change_password.html',{'msg':msg})

@auth_customer
def prod_details(request,pid):
    msg = ''
    product_details = Product.objects.get(id = pid)

    if request.method == 'POST':
        # checking if the user has added the same product in cart
        # exists() method returns boolean value, true if data exists
        product_exist = Cart.objects.filter(product_details = pid,customer = request.session['customer']).exists()

        if not product_exist:
            cart = Cart(customer_id = request.session['customer'], product_details_id = pid)
            cart.save()
        else:
            msg = 'item already in cart'

      # data we pass views to templete is called context data
    context = {
        'details':product_details,
        'msg':msg
    }
    return render(request, 'customer/product_details.html', context)
    # return render(request, 'customer/product_details.html',{'details':product_details,'msg':msg})

@auth_customer
def customer_cart(request):
    if 'customer' in request.session: # setting the customer session, to block customer activities before login
        cart = Cart.objects.filter(customer = request.session['customer'])
        return render(request, 'customer/cart.html',{'customer_cart' : cart})
    else:
        return redirect('common:customerlogin')

@auth_customer
def customer_orders(request):
    return render(request, 'customer/orders.html')

@auth_customer
def profile(request):
    profile = Customer.objects.get(id = request.session['customer'])

    return render(request, 'customer/profile.html',{'customer' : profile})

# to logout and remove item from cart have no html. these are two functions to do the task.
# remove item has url, it is done by using id
@auth_customer
def remove_item_from_cart(request,pid):
    cart_item = Cart.objects.get(product_details = pid, customer = request.session['customer'])
    cart_item.delete()
    return redirect('customer:cart')
@auth_customer
def logout(request):
    del request.session['customer']
    request.session.flush() # to remove session data from django_session table
    return redirect('common:customerlogin')

customer/templates/customer/cart.html
{% extends 'customer/customer_master.html' %}

{% load static %}

{% block content %}
<div class="text-center p-4">
    <h1>MY CART</h1>
</div>
<div class="container">
<div class="row">
    
    <div class="">
        
        <table class="table">
            {% if customer_cart %}
            <thead>
            <th>Product Name</th>
            <th>Discription</th>
            <th>Quantity</th>
            <th>Total Price</th>
            <th>image</th>
            <th>Order Status</th>
            <!-- <th>Status</th> -->
            </thead>
            {% for cart in customer_cart %}
            
            <tr class="table-active">
                <td>{{cart.product_details.product_name}}</td>
                <td>{{cart.product_details.product_description}}</td>
                <td><input type="number"></td>
                <td>{{cart.product_details.product_price}}</td>
                <td><img src="{{cart.product_details.product_image.url}}" class="card-img-top" alt="..." height="100px" width="100px"></td>
                <td><a href="{% url 'customer:remove_cart' cart.product_details.id %}">Remove</a></td>
            </tr>
        
            {% endfor %}
        </table>
        {% else %}
        <h1>Cart is Empty</h1>
        {% endif %}
    </div>
   </div>
</div>
{% endblock %}

customer/templates/customer/change_password.html
{% extends 'customer/customer_master.html' %}

{% load static %}

{% block content %}
<br><br><br>
<section class="changePassword">
<form method="POST">
  {% csrf_token %}
    <div class="mb-3">
      <label for="exampleInputPassword1" class="form-label">Current Password</label>
      <input type="password" class="form-control" id="exampleInputPassword1" name="current_password"><br>
    </div><br><br>
    <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">New Password</label>
        <input type="password" class="form-control" id="exampleInputPassword1" name="new_password"><br>
      </div><br><br>
      <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Confirm Password</label>
        <input type="password" class="form-control" id="exampleInputPassword1" name="confirm_password"><br>
      </div><br><br>
    <button type="submit" class="btn btn-success">Submit</button>
    {{msg}}
  </form>
</section>
<br><br><br>

{% endblock %}

customer/templates/customer/customer_home.html
{% extends 'customer/customer_master.html' %}

{% load static %}

{% block content %}
<!-- <style>
    img{
    width: 200px;
    height: 200px;
    margin: 0 auto;
    display: block;
    
}
.gallary{
    margin-left: 150px;
    text-align: center;
    padding: 30px 30px;

}
.btn-outline-success{
    width: 100px;
    height: 40px;
}
button{
    text-align: center;
    font-size: 15px;
    color: black;
    width: 200px;
    padding: 15px;
    border: 0;
    outline: none;
    cursor: pointer;
    margin-top: 5px;
    border-radius: 20px;
}
.buy-1{
    background: #2183a2;
}

</style>

<div class="row">
    <div class="col-lg-3">
        <div class="gallary">
            <div class="content">
                <img src="{% static 'images/shoes.jpeg' %}" alt="">
                <h3>Shoes</h3>
                <h6>$100.00</h6>
                <p><a href="/customer/productDetails">Know more</a></p>
                <button class="buy-1" type="submit">Add to Cart</button>
            </div>
        </div>
        <div class="gallary">
            <div class="content">
                <img src="{% static 'images/plant.webp' %}" alt="">
                <h3>Plants</h3>
                <h6>$50.00</h6>
                <p><a href="/customer/productDetails">Know more</a></p>
                <button class="buy-1" type="submit">Add to Cart</button>
            </div>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="gallary">
            <div class="content">
                <img src="{% static 'images/iph.jpg' %}" alt="">
                <h3>Phones</h3>
                <h6>$200.00</h6>
                <p><a href="/customer/productDetails">Know more</a></p>
                <button class="buy-1" type="submit">Add to Cart</button>
            </div>
        </div>
        <div class="gallary">
            <div class="content">
                <img src="{% static 'images/makeup.jpg' %}" alt="">
                <h3>Cosmetics</h3>
                <h6>$120.00</h6>
                <p><a href="/customer/productDetails">Know more</a></p>
                <button class="buy-1" type="submit">Add to Cart</button>
            </div>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="gallary">
            <div class="content">
                <img src="{% static 'images/bags.jpeg' %}" alt="">
                <h3>Bags</h3>
                <h6>$110.00</h6>
                <p><a href="/customer/productDetails">Know more</a></p>
                <button class="buy-1" type="submit">Add to Cart</button>
            </div>
        </div>
        <div class="gallary">
            <div class="content">
                <img src="{% static 'images/dress.webp' %}" alt="">
                <h3>Ethnical</h3>
                <h6>$200.00</h6>
                <p><a href="/customer/productDetails">Know more</a></p>
                <button class="buy-1" type="submit">Add to Cart</button>
            </div>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="gallary">
            <div class="content">
                <img src="{% static 'images/jean.jpg' %}" alt="">
                <h3>Jeans</h3>
                <h6>$90.00</h6>
                <p><a href="/customer/productDetails">Know more</a></p>
                <button class="buy-1" type="submit">Add to Cart</button>
            </div>
        </div>
        <div class="gallary">
            <div class="content">
                <img src="{% static 'images/gro.jpg' %}" alt="">
                <h3>Grocery</h3>
                <h6>$50.00</h6>
                <p><a href="/customer/productDetails">Know more</a></p>
                <button class="buy-1" type="submit">Add to Cart</button>
            </div>
        </div>
    </div>   
</div> -->
<br><br><br>
<div class="col-md-10">
    <div class="row">
        {% for products in products %}
    <div class="col-4">
        <div class="card" style="width: 18rem;">
            <img src="{{products.product_image.url}}" class="card-img-top" alt="..." height="200px" width="200px">
            <div class="card-body">
                <h5 class="card-title">{{products.product_name|title}}</h5>
                <p class="card-text">{{products.product_description|title}}</p>
                <a href="{% url 'customer:productDetails' products.id %}" class="btn btn-primary">Details</a>
                <p>seller: {{products.seller.seller_name|title}}</p>
            </div>
        </div>
    </div>
    {% endfor %}
    </div>
    </div>   
<br><br><br> 

{% endblock %}

customer/templates/customer/customer_master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Customer</title>
    <link rel="stylesheet" href="{% static 'css/styleCustomer.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/01741b9219.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">ECOMApp</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/customer/customerhome">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/customer/profile">Profile</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="/customer/cart">Cart</a>
              </li>
              <!-- <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Prime
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li> -->
              <!-- <li class="nav-item">
                <a class="nav-link disabled">Disabled</a>
              </li> -->
              <li class="nav-item">
                <a class="nav-link active" href="/customer/orders">Orders</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="/customer/changePassword">Change Password</a>
              </li>
            </ul>
            <!-- <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form> -->
            <button class="btn btn-outline-success" type="submit"><a href="{% url 'customer:logout' %}">LOGOUT</a></button>
          </div>
        </div>
      </nav>
      {% block content %}

      
      {% endblock%}
</body>

<footer>
    <div class="row">
        <div class="col">
            <h3>ECOMApp</h3>
            <p>agdjhskhdlsjklskl;<br>dgshdkjlkd<br>jhddkll;sak;l;.</p>
        </div>
        <div class="col">
            <h3>Office</h3>
            <p>ABC Road</p>
            <p>While Field, ABCD</p>
            <p>Kerala, PIN 673501, India</p>
            <p class="email-id">abcd@gmail.com</p>
            <p>+91 - 01234567</p>
        </div>
        <div class="col">
            <h3>Links</h3>
            <ul>
                <li><a href="#">About Us</a></li>
                <li><a href="#">Services</a></li>
                <li><a href="#">Clients</a></li>
                <li><a href="#">Awards</a></li>
                <li><a href="#">Blog</a></li>
            </ul>
        </div>
        <div class="col">
            <h3>Newsletter</h3>
            <form action="">
                <i class="fa-regular fa-envelope"></i>
                <input type="email" placeholder=" Enter your email id" required>
                <button type="submit"><i class="fa-solid fa-arrow-right"></i></button>
            </form>
            <div class="social-icons">
                <i class="fa-brands fa-square-facebook"></i>
                <i class="fa-brands fa-square-twitter"></i>
                <i class="fa-brands fa-square-whatsapp"></i>
                <i class="fa-brands fa-square-instagram"></i>
            </div>
        </div>
    </div>
    <hr>
    <p class="copyright">©ECOMApp Ltd 2022</p>
</footer>
</html>

customer/templates/customer/orders.html
{% extends 'customer/customer_master.html' %}

{% load static %}

{% block content %}

<div class="text-center p-4">
    <h1>MY ORDERS</h1>
</div>
<div class="container">
<div class="row">
    
    <div class="">
        <table class="table">
            <thead>
            <th>Sl.no</th>
            <th>Product Name</th>
            <th>Discription</th>
            <th>Quantity</th>
            <th>price</th>
            <th> Order Status</th>
            </thead>
            <tbody>
            <tr class="table-active">
            </tr>
            </tbody>
        </table>
    </div>

</div>
</div>
{% endblock %}

customer/templates/customer/product_details.html
{% extends 'customer/customer_master.html' %}

{% load static %}

{% block content %}
<style>
    .tb1{
        width: 100%;
        text-align: center;
        padding: 2px;
    }
</style>
<br><br><br>
<section class="banner-left">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-12 col-lg-6">
                <div class="banner-content">
                    <div
                        style="float:right; background-color:black; width:700px; height:400px; border-radius:250px;margin-right: -100px;">
                        <center><img src="{{details.product_image.url}}" alt="" height="300px" width="200px"
                                style="margin-top: 50px;"></center>
                    </div>
                </div>
            </div>
            <div class="col-lg-6" style="float: right;">
                <div class="mb-3"
                    style="background-color:black; color: white; width:700px; height:400px; border-radius:250px; margin-left: 100px; text-align: center;">
                    <center style="padding: 25px;">
                        <form method="POST">
                            {% csrf_token %}
                            <table class="tb1">

                                <tr>
                                    <td><h4 style=" margin-top:100px;">{{details.product_name|title}}</h4></td>
                                </tr>
                                <tr><td>Product Description: {{details.product_description|title}}</td></tr>
                                <tr><td>Price: {{details.product_price}}</td></tr>
                                <tr><td><button type="submit" class="btn btn-primary">Add to Cart</button></td></tr>
                                <tr><td>{{msg}}</td></tr>
                            </table>
                        </form>
                        <br><br>
                    </center>
                </div>
                <a href="{% url 'customer:customerhome' %}">Continue Shopping</a>
            </div>
        </div>
    </div>
    
</section>

<!-- <section>
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <div class="catalogues">
                    <div class="cat-1">
                        <img src="{{details.product_image.url}}" alt="" height="300px" width="200px" style="margin-top: 50px;">

                        <form method="POST">
                            {% csrf_token %}
                            
                        <h4 style=" margin-top:80px">{{details.product_name}}</h4><br>
                        <p>Product description:{{details.product_description}}<br>
                        <p>Price:{{details.product_price}}</p><br>
                        <button type="submit" class="btn btn-primary">Add to Cart</button>
                            {{msg}}
                    </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section> -->


<br><br><br>
{% endblock %}

customer/templates/customer/profile.html
{% extends 'customer/customer_master.html' %}

{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Customer profile</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</head>
<body>
    <div>
        <img src="{{customer.customer_image.url}}" alt="" width="200px" height="200px" style="border-radius: 30px;">
    
        <p>Name: {{customer.customer_name}} </p>
        <p>E-mail: {{customer.customer_email}} </p>
        <p>Phone: {{customer.customer_phone}} </p>
        <p>Address: {{customer.customer_address}}</p>
        <p>Gender: {{customer.customer_gender}}</p>
    </div>
</body>
</html>


{% endblock %}