common/urls.py
from django.urls import path
from . import views

app_name = 'common'
urlpatterns = [
    path('projecthome', views.project_home, name='projecthome'),
    path('customerlogin', views.customer_login, name='customerlogin'),
    path('sellerlogin', views.seller_login, name='sellerlogin'),
    path('customer_reg', views.customer_registration, name='customer_reg'),
    path('seller_reg', views.seller_registration, name='seller_reg'),                                                                       
    path('email_exist', views.email_exist, name='email_exist'),                                                       
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('common/', include('common.urls')),
    path('customer/', include('customer.urls')),
    path('ecom_admin/', include('ecom_admin.urls')),
    path('seller/', include('seller.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

seller/urls.py
from django.urls import path
from . import views

app_name='seller'
urlpatterns=[
    path('sellerhome', views.seller_home, name='sellerhome'),
    path('addproduct', views.add_product, name='addproduct'),
    path('changePassword', views.change_password, name='changePassword'),
    path('catalogue', views.catalogue, name='catalogue'),
    path('dashboard', views.dash_board, name='dashboard'),
    path('profile', views.seller_profile, name='profile'),
    path('updateStock', views.update_stock, name='updateStock'),
    path('recentOrder', views.recent_order, name='recentOrder'),
    path('orderHistory', views.order_history, name='orderHistory'),
    path('get_stock', views.get_stock, name='get_stock'),   # url in which Ajax call is made, to update stock
]

seller/models.py
from django.db import models
from common.models import Seller

# Create your models here.
class Product(models.Model):
    seller = models.ForeignKey(Seller, on_delete=models.CASCADE)
    product_name = models.CharField(max_length=50)
    product_description = models.CharField(max_length=100)
    product_number = models.BigIntegerField()
    product_price = models.FloatField()
    current_stock = models.BigIntegerField(default=1)
    product_image = models.ImageField(upload_to='product')

seller/views.py
from django.shortcuts import render,redirect
from common.models import Seller
from .models import Product
from django.http import JsonResponse

# Create your views here.
def seller_home(request):
    seller_data = Seller.objects.get(id = request.session['seller'])
    return render(request, 'seller/seller_home.html',{'data':seller_data})

def add_product(request):
    msg = ''
    if request.method == 'POST':
            product_name = request.POST['product_name']
            product_description = request.POST['product_description']
            product_number = request.POST['product_number']
            product_price = request.POST['product_price']
            current_stock = request.POST['current_stock']
            product_image = request.FILES['product_image']

            product = Product(product_name=product_name,
            product_description=product_description,
            product_number=product_number,
            product_price=product_price,
            current_stock=current_stock,
            product_image=product_image,
            seller_id=request.session['seller'])

            product.save()
            msg = 'Product added successfully'

    return render(request, 'seller/add_product.html',{'msg':msg})

def change_password(request):
    msg = ''
    if request.method == 'POST':
        seller = Seller.objects.get(id = request.session['seller'])

        seller_password = request.POST['current_password']
        new_password = request.POST['new_password']
        confirm_password = request.POST['confirm_password']

        if seller.seller_password == seller_password:
            if new_password == confirm_password:
                seller.seller_password = new_password
                seller.save()
                msg = 'Password changed successfully'
            else:
                msg = 'Password Does not Match'
        else:
            msg = 'Incorrect password'
            
    return render(request, 'seller/change_password.html',{'msg':msg})

def catalogue(request):
    seller_products = Product.objects.filter(seller = request.session['seller'])
    return render(request, 'seller/catalogue.html',{'products':seller_products})

def seller_profile(request):
    profile = Seller.objects.get(id = request.session['seller'])
    return render(request, 'seller/seller_profile.html',{'seller':profile})

def update_stock(request):

    update_stock = Product.objects.filter(seller = request.session['seller'])
    
    # write this if condition to add new stock with current stock
    if request.method =='POST':
        new_stock = request.POST['NewStock']
        product_id = request.POST['product_id']

        product = Product.objects.get(id = product_id)
        product.current_stock = product.current_stock + int(new_stock)
        product.save()
    return render(request, 'seller/update_stock.html', {'products':update_stock})

def recent_order(request):
    return render(request, 'seller/recent_order.html')

def dash_board(request):
    return render(request, 'seller/dashboard.html')

def order_history(request):
    return render(request, 'seller/order_history.html')

def logout(request):
    del request.session['seller']
    request.session.flush() # to remove session data from django_session table
    return redirect('common:sellerlogin')

# this is a funtion to update stock in seller (done with update_stock.html using Ajax)
def get_stock(request):
    id = request.POST['id']
    product = Product.objects.get(id=id)
    product_name = product.product_name
    current_stock = product.current_stock
    p_id = product.id
    return JsonResponse({'p_name':product_name, 'stock':current_stock,'p_id':p_id})

seller/templates/seller/add_product.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Seller registration</title>
    <!-- <link rel="stylesheet" href="{% static 'css/login.css' %}"> -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

    <style>
      *{
      padding: 2px;
      margin: 30px;
      /* box-sizing: border-box; */
      }
      body{
          background: rgb(70, 123, 154);
      }
      </style>
</head>
<body>
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{msg}}
        <div class="mb-3">
            <label for="exampleInputName" class="form-label">Product Name</label>
            <input type="text" class="form-control" id="exampleInputName" name="product_name">
          </div>
          <div class="mb-3">
            <label for="exampleInputDescription" class="form-label">Product Description</label>
            <textarea id="exampleInputDescription" class="form-control" name="product_description" rows="4" cols="50"></textarea>
            <!-- <input type="text" class="form-control" id="exampleInputAddress"> -->
          </div>
        <div class="mb-3">
            <label for="exampleInputProductNumber" class="form-label">Product Number</label>
            <input type="number" class="form-control" id="exampleInputProductNumber" name="product_number">
          </div>
       
        <div class="mb-3">
            <label for="exampleInputPrice" class="form-label">Product Price</label>
            <input type="number" class="form-control" id="exampleInputPrice" name="product_price">
        </div>
        <div class="mb-3">
            <label for="CurrentStoke" class="form-label">Current Stoke</label>
            <input type="number" class="form-control" id="CurrentStoke" name="current_stock">
        </div>
        
          <div class="mb-3">
            <label for="exampleInputFile" class="form-label">Product Image</label>
            <input type="file" class="form-control" id="exampleInputFile" name="product_image">
          </div>
        
    
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
</body>
</html>

seller/templates/seller/catalogue.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Catalogue</title>
    <link rel="stylesheet" href="{% static 'css/stylecatalogue.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/01741b9219.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">ECOMApp</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <button class="btn btn-outline-success" type="submit"><a href="#">LOGOUT</a></button>
        </div>
    </nav>     
   <div class="col-md-10">
    <div class="row">
        {% for products in products %}
    <div class="col-4">
        <div class="card" style="width: 18rem;">
            <img src="{{products.product_image.url}}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">{{products.product_name|title}}</h5>
                <p class="card-text">{{products.product_description|title}}</p>
                <a href="#" class="btn btn-primary">Go somewhere</a>
            </div>
        </div>
    </div>
    {% endfor %}
    </div>
    </div>    

</body>
<footer  style="background-color: black; color: white;text-decoration: none;">
    <div class="row">
        <div class="col">
            <h3>ECOMApp</h3>
            <p>agdjhskhdlsjklskl;<br>dgshdkjlkd<br>jhddkll;sak;l;.</p>
        </div>
        <div class="col">
            <h3>Office</h3>
            <p>ABC Road</p>
            <p>While Field, ABCD</p>
            <p>Kerala, PIN 673501, India</p>
            <p class="email-id">abcd@gmail.com</p>
            <p>+91 - 0123456798</p>
        </div>
        <div class="col">
            <h3>Links</h3>
            <ul>
                <li><a href="#">About Us</a></li>
                <li><a href="#">Services</a></li>
                <li><a href="#">Clients</a></li>
                <li><a href="#">Awards</a></li>
                <li><a href="#">Blog</a></li>
            </ul>
        </div>
        <div class="col">
            <h3>Newsletter</h3>
            <form action="">
                <i class="fa-regular fa-envelope"></i>
                <input type="email" placeholder=" Enter your email id" required>
                <button type="submit"><i class="fa-solid fa-arrow-right"></i></button>
            </form>
            <div class="social-icons">
                <i class="fa-brands fa-square-facebook"></i>
                <i class="fa-brands fa-square-twitter"></i>
                <i class="fa-brands fa-square-whatsapp"></i>
                <i class="fa-brands fa-square-instagram"></i>
            </div>
        </div>
    </div>
    <hr>
    <p class="copyright" style="text-align: center;">©ECOMApp Ltd 2022</p>
</footer>
</html>

seller/templates/seller/change_password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>seller change password</title>
    <link rel="stylesheet" href="{% static 'css/sellerhome.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/01741b9219.js"></script>
    <style>
      *{
      padding: 2px;
      margin: 20px;
      /* box-sizing: border-box; */
      }
      body{
          background: rgb(70, 123, 154);
      }
      </style>
</head>
<body>
    <section class="changePassword" style="background-color:  rgb(70, 123, 154);">
        <form method="POST">
          {% csrf_token %}
            <div class="mb-3">
              <label for="exampleInputPassword1" class="form-label">Current Password</label>
              <input type="password" class="form-control" id="exampleInputPassword1" name="current_password"><br>
            </div><br><br>
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">New Password</label>
                <input type="password" class="form-control" id="exampleInputPassword1" name="new_password"><br>
              </div><br><br>
              <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">Confirm Password</label>
                <input type="password" class="form-control" id="exampleInputPassword1" name="confirm_password"><br>
              </div><br><br>
            <button type="submit" class="btn btn-success">Submit</button>
            {{msg}}
          </form>
        </section>
        <br><br><br>
</body>
</html>

seller/templates/seller/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    <link rel="stylesheet" href="{% static 'css/dashstyle.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxst.icons8.com/vue-static/landings/line-awesome/font-awesome-line-awesome/css/all.min.css">
</head>
<body>
    <div class="sidebar">
        <div class="sidebar-brand">
            <h1>ECOMApp</h1>
        </div>
        <div class="sidebar-menu">
            <ul>
                <li>
                    <a href="#"><span class="las la-igloo"></span>
                    <span>Profile</span></a>
                </li>
                <li>
                    <a href="{% url 'seller:sellerhome' %}"><span class="las la-home"></span>
                    <span>Home</span></a>
                </li>
                <li>
                    <a href="#"><span class="las la-catalogue"></span>
                    <span>Catalogue</span></a>
                </li>
                <li>
                    <a href="{% url 'seller:addproduct' %}"><span class="las la-addproduct"></span>
                    <span>Add Product</span></a>
                </li>
                <li>
                    <a href="#"><span class="las la-updatestoke"></span>
                    <span>Update Stoke</span></a>
                </li>
                <li>
                    <a href="#"><span class="las la-currentstoke"></span>
                    <span>Current Stoke</span></a>
                </li>
                <li>
                    <a href="{% url 'seller:changePassword' %}"><span class="las la-logout"></span>
                    <span>Change Password</span></a>
                </li>
                <li>
                    <a href=""><span class="las la-changepassword"></span>
                    <span>Logout</span></a>
                </li>
            </ul>
        </div>
    </div>
    
    <div class="main-content">
        <header>
            <h4 style="color: black;">welcome</h4>
        </header>
    </div>
</body>
</html>

seller/templates/seller/order_history.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Order History</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    <div class="text-center p-4">
        <h1>ORDER HISTORY</h1>
    </div>
<div class="container">
    <div class="row">
        
        <div class="">
            <table class="table">
                <thead>
                <th>sl.no</th>
                <th>Product Number</th>
                <th>Product Name</th>
                </thead>
                <tbody>
                <tr>
                </tr>
                </tbody>
            </table>
        </div>

    </div>
</div>
</body>
</html>

seller/templates/seller/recent_order.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Recent order</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/01741b9219.js"></script>
    <style>
        .div1{
            margin-top: 100px;
            margin-left: 400px;
            margin-right: 400px;
        }
    </style>
</head>
<body style="background-color:  rgb(70, 123, 154);;">
    <div class="div1">
      <form>
        <div class="mb-3">
        <label for="exampleInputProductNumber" class="form-label">Product Number</label>
        <select class="form-select" aria-label="Default select example">
            <option selected>select</option>
            <option value="1">One</option>
            <option value="2">Two</option>
            <option value="3">Three</option>
          </select>
        </div>
        <div class="mb-3">
          <label for="exampleInputCurrentStock" class="form-label">Recent order</label>
          <input type="text" class="form-control" id="exampleInputCurrentStock" aria-describedby="">
        </div>
        <div class="mb-3">
          <label for="exampleInputNewStock" class="form-label">New Stock</label>
          <input type="password" class="form-control" id="exampleInputNewStock">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
    </div>
</body>
</html>

seller/templates/seller/seller_home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Seller home</title>
    <link rel="stylesheet" href="{% static 'css/homeseller.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/01741b9219.js"></script>
</head>
<body style="background-color: rgb(70, 123, 154);">
    
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">ECOMApp</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <button class="btn btn-outline-success" type="submit"><a href="{% url 'common:sellerlogin' %}">LOGOUT</a></button>
        </div>
    </nav>   
    {% block content %}
    <div class="col-1">
        <h2>WELCOME {{data.seller_name}}</h2>
        <p></p>
    </div>
    {% endblock %}

        <div class="div1">
            <center>
                <div><img src="{% static 'images/sellerprof.webp' %}" alt="" width="300px" height="300px" style="border-radius: 200px; padding-top:10px;"></div>
            </center>
        

            <div class="list-group" id="id1">
                <a id="a1" href="{% url 'seller:sellerhome' %}" class="list-group-item list-group-item-action list-group-item-primary" style="color: black;">Home</a>
                <a id="a1" href="{% url 'seller:profile' %}" class="list-group-item list-group-item-action list-group-item-primary" style="color: black;">Profile</a>
                <a id="a1" href="{% url 'seller:catalogue' %}" class="list-group-item list-group-item-action list-group-item-primary" style="color: black;">Catalogue</a>
                <a id="a1" href="{% url 'seller:addproduct' %}" class="list-group-item list-group-item-action list-group-item-primary" style="color: black;">Add Product</a>
                <a id="a1" href="{% url 'seller:updateStock' %}" class="list-group-item list-group-item-action list-group-item-primary" style="color: black;">Update Stoke</a>
                <a id="a1" href="{% url 'seller:recentOrder' %}" class="list-group-item list-group-item-action list-group-item-primary" style="color: black;">Recent Orders</a>
                <a id="a1" href="{% url 'seller:orderHistory' %}" class="list-group-item list-group-item-action list-group-item-primary" style="color: black;">Order History</a>
                <a id="a1" href="{% url 'seller:changePassword' %}" class="list-group-item list-group-item-action list-group-item-primary" style="color: black;">Change Password</a>
            </div>
        </div>
        
</body>
<br><br><br>
<footer>
    <div class="row">
        <div class="col">
            <h3>ECOMApp</h3>
            <p>agdjhskhdlsjklskl;<br>dgshdkjlkd<br>jhddkll;sak;l;.</p>
        </div>
        <div class="col">
            <h3>Office</h3>
            <p>ABC Road</p>
            <p>While Field, ABCD</p>
            <p>Kerala, PIN 673501, India</p>
            <p class="email-id">abcd@gmail.com</p>
            <p>+91 - 0123456798</p>
        </div>
        <div class="col">
            <h3>Links</h3>
            <ul>
                <li><a href="#">About Us</a></li>
                <li><a href="#">Services</a></li>
                <li><a href="#">Clients</a></li>
                <li><a href="#">Awards</a></li>
                <li><a href="#">Blog</a></li>
            </ul>
        </div>
        <div class="col">
            <h3>Newsletter</h3>
            <form action="">
                <i class="fa-regular fa-envelope"></i>
                <input type="email" placeholder=" Enter your email id" required>
                <button type="submit"><i class="fa-solid fa-arrow-right"></i></button>
            </form>
            <div class="social-icons">
                <i class="fa-brands fa-square-facebook"></i>
                <i class="fa-brands fa-square-twitter"></i>
                <i class="fa-brands fa-square-whatsapp"></i>
                <i class="fa-brands fa-square-instagram"></i>
            </div>
        </div>
    </div>
    <hr>
    <p class="copyright">©ECOMApp Ltd 2022</p>
</footer>
</html>

seller/templates/seller/update_stock.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Stocke</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/01741b9219.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.1.js" integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=" crossorigin="anonymous"></script>
    <style>
        .div1{
            margin-top: 100px;
            margin-left: 400px;
            margin-right: 400px;
        }
    </style>
</head>
<body style="background-color:  rgb(70, 123, 154);;">
    <div class="div1">
      <form method="POST">
        {% csrf_token %}
        <div class="mb-3">
        <label for="exampleInputProductNumber" class="form-label">Product Number</label>
        <select class="form-select" aria-label="Default select example" id="stock">
          <option value="" selected disabled>selected</option>
          {% for product_number in products %}
            <option value="{{product_number.id}}">{{product_number.product_number}}</option>
            {% endfor %}
          </select>
          <input type="hidden" id="p_id" name="product_id">
        </div>
        <div class="mb-3">
          <label for="exampleInputProductName" class="form-label">product Name</label>
          <input type="text" class="form-control" id="ProductName" readonly aria-describedby="">
        </div>
        <div class="mb-3">
          <label for="exampleInputCurrentStock" class="form-label">Current Stock</label>
          <input type="number" class="form-control" id="CurrentStock" readonly aria-describedby="">
        </div>
        <div class="mb-3">
          <label for="exampleInputNewStock" class="form-label">New Stock</label>
          <input type="number" class="form-control" id="NewStock" name="NewStock">
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
      </form>
    </div>


    <script>
      $('#stock').change(function(){
        $.ajaxSetup({ // passing csrf_token is ajax request
          headers: {
            "X-CSRFToken": $('[name=csrfmiddlewaretoken]').val()
        }
      })

        $.ajax({
          url:"{% url 'seller:get_stock' %}", // url in which ajax call is made
          type:'POST', 
          data:{
            id:$(this).val() 
          },
          success:function(response){
              // console.log(response.p_name)
              // console.log(response.stock)
              $('#ProductName').val(response.p_name)
              $('#CurrentStock').val(response.stock)
              $('#p_id').val(response.p_id)
          }
        })
      })
    </script>
</body>
</html>