common/urls.py
from django.urls import path
from . import views

app_name = 'common'
urlpatterns = [
    path('projecthome', views.project_home, name='projecthome'),
    path('customerlogin', views.customer_login, name='customerlogin'),
    path('sellerlogin', views.seller_login, name='sellerlogin'),
    path('customer_reg', views.customer_registration, name='customer_reg'),
    path('seller_reg', views.seller_registration, name='seller_reg'),                                                                       
    path('email_exist', views.email_exist, name='email_exist'),                                                       
]

ecom_admin/urls.py
from django.urls import path
from . import views

app_name = 'ecom_admin'
urlpatterns=[
    path('adminhome', views.admin_home, name='adminhome'),
    path('approveCustomer', views.approve_customer, name='approveCustomer'),
    path('approveSeller', views.approve_seller,name='approveSeller'),
    path('viewCustomer', views.view_customer, name='viewCustomer'),
    path('viewSeller', views.view_seller, name='viewSeller'),
    path('approve/<int:sid>', views.approve, name='approve'),

]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('common/', include('common.urls')),
    path('customer/', include('customer.urls')),
    path('ecom_admin/', include('ecom_admin.urls')),
    path('seller/', include('seller.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ecom_admin/models.py
from django.db import models

# Create your models here.

ecom_admin/views.py
from django.shortcuts import render,redirect
from common.models import Customer,Seller
from django.core.mail import send_mail
from django.conf import settings

# Create your views here.
def admin_home(request):
    return render(request, 'ecom_admin/home_admin.html')

def approve_customer(request):
    customers = Customer.objects.all()# every objects in customer class stores here.
    return render(request, 'ecom_admin/approve_customer.html', {'customer_list' : customers})

def approve_seller(request):
    seller = Seller.objects.all()
    return render(request, 'ecom_admin/approve_seller.html',{'seller_list':seller})

def view_customer(request):
    return render(request, 'ecom_admin/view_customer.html')

def view_seller(request):
    return render(request, 'ecom_admin/view_seller.html')

def approve(request,sid):

    seller = Seller.objects.get(id=sid)
    email = Seller.objects.filter(seller_email = request.session['seller'])
    message = 'You are approved to login'
    send_mail(
        'Approved',
        message,
        settings.EMAIL_HOST_USER,
        [seller.seller_email,],
        
    )
    seller.approved = True
    seller.save()
    return redirect('ecom_admin:viewSeller')

ecom_admin/templates/ecom_admin/approve_customer.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>approve_cust</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>

    <div class="text-center p-4">
        <h1>APPROVE CUSTOMER</h1>
    </div>
<div class="container">
    <div class="row">
        
        <div class="">
            <table class="table">
                <thead>
                <th>Full Name</th>
                <th>Email</th>
                <th>Phone Number</th>
                <th>Address</th>
                <th>Gender</th>
                <th>Password</th>
                <th>Status</th>
                <th>Remove</th>
                </thead>
                <tbody>
                {% for customer in customer_list %}
                <tr class="table-active">
                    <td>{{customer.customer_name}}</td>
                    <td>{{customer.customer_email}}</td>
                    <td>{{customer.customer_phone}}</td>
                    <td>{{customer.customer_address}}</td>
                    <td>{{customer.customer_gender}}</td>
                    <td>{{customer.customer_password}}</td>
                    <td><button type="button" class="btn btn-success">Approve</button></td>
                    <td><button type="button" class="btn btn-danger">Remove</button></td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

    </div>
</div>
</body>
</html>

ecom_admin/templates/ecom_admin/approve_seller.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>approve_seller</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    <div class="text-center p-4">
        <h1>APPROVE SELLER</h1>
    </div>
<div class="container">
    <div class="row">
        
        <div class="">
            <table class="table">
                <thead>
                <th>Seller Name</th>
                <th>Address</th>
                <th>Phone Number</th>
                <th>Email</th>
                <th>Company Name</th>
                <th>Account Holder Name</th>
                <th>IFSC</th>
                <th>Branch</th>
                <th>Account Number</th>
                <th>User Name</th>
                <th>Password</th>
                <th>Image</th>
                <th>Status</th>
                <th>Remove</th>
                </thead>
                    <tbody>
                        {% for seller in seller_list %}
                        <tr class="table-active">
                            <td>{{seller.seller_name}}</td>
                            <td>{{seller.seller_address}}</td>
                            <td>{{seller.seller_phone}}</td>
                            <td>{{seller.seller_email}}</td>
                            <td>{{seller.company_name}}</td>
                            <td>{{seller.acc_holdername}}</td>
                            <td>{{seller.ifsc}}</td>
                            <td>{{seller.branch}}</td>
                            <td>{{seller.acc_number}}</td>
                            <td>{{seller.seller_username}}</td>
                            <td>{{seller.seller_password}}</td>
                            <td><img src="{{seller.seller_pic.url}}" alt="" height="100px" width="100px"></td>
                            <td>
                                {% if not seller.approved %}
                                <button type="submit" class="btn btn-success"><a href="{% url 'ecom_admin:approve' seller.id %}">Approve</a></button>
                                {% endif %}
                            </td>
                            <td><button type="button" class="btn btn-danger">Remove</button></td>
                        </tr>
                        {% endfor %}
                    </tbody>
            </table>
        </div>

    </div>
</div>
</body>
</html>

ecom_admin/templates/ecom_admin/home_admin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin home</title>
    <link rel="stylesheet" href="{% static 'css/adminhome.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/01741b9219.js"></script>
</head>
<body style="background-color: rgb(59, 66, 67);">

    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">ECOMApp</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <button class="btn btn-outline-success" type="submit"><a href="#">LOGOUT</a></button>
        </div>
    </nav>   

        <div class="div1">
            <center>
                <div><img src="{% static 'images/ad.jpg' %}" alt="" width="300px" height="300px" style="border-radius: 200px; padding-top:10px;"></div>
            </center>
        

            <div class="list-group" id="id1">
                <a id="a1" href="{% url 'ecom_admin:adminhome' %}" class="list-group-item list-group-item-action list-group-item-primary" style="color: black;">Home</a>
                <a id="a1" href="{% url 'ecom_admin:approveCustomer' %}" class="list-group-item list-group-item-action list-group-item-primary" style="color: black;">Approve customer</a>
                <a id="a1" href="{% url 'ecom_admin:approveSeller' %}" class="list-group-item list-group-item-action list-group-item-primary" style="color: black;">Approve Seller</a>
                <a id="a1" href="{% url 'ecom_admin:viewCustomer' %}" class="list-group-item list-group-item-action list-group-item-primary" style="color: black;">View Customer</a>
                <a id="a1" href="{% url 'ecom_admin:viewSeller' %}" class="list-group-item list-group-item-action list-group-item-primary" style="color: black;">View Seller</a>
            </div>
        </div>
</body><footer>
    <div class="row">
        <div class="col">
            <h3>ECOMApp</h3>
            <p>agdjhskhdlsjklskl;<br>dgshdkjlkd<br>jhddkll;sak;l;.</p>
        </div>
        <div class="col">
            <h3>Office</h3>
            <p>ABC Road</p>
            <p>While Field, ABCD</p>
            <p>Kerala, PIN 673501, India</p>
            <p class="email-id">abcd@gmail.com</p>
            <p>+91 - 01234567</p>
        </div>
        <div class="col">
            <h3>Links</h3>
            <ul>
                <li><a href="#">About Us</a></li>
                <li><a href="#">Services</a></li>
                <li><a href="#">Clients</a></li>
                <li><a href="#">Awards</a></li>
                <li><a href="#">Blog</a></li>
            </ul>
        </div>
        <div class="col">
            <h3>Newsletter</h3>
            <form action="">
                <i class="fa-regular fa-envelope"></i>
                <input type="email" placeholder=" Enter your email id" required>
                <button type="submit"><i class="fa-solid fa-arrow-right"></i></button>
            </form>
            <div class="social-icons">
                <i class="fa-brands fa-square-facebook"></i>
                <i class="fa-brands fa-square-twitter"></i>
                <i class="fa-brands fa-square-whatsapp"></i>
                <i class="fa-brands fa-square-instagram"></i>
            </div>
        </div>
    </div>
    <hr>
    <p class="copyright">©ECOMApp Ltd 2022</p>
</footer>
</html>

ecom_admin/templates/ecom_admin/view_customer.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>viewCustomer</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    <div class="text-center p-4">
        <h1>VIEW CUSTOMER</h1>
    </div>
<div class="container">
    <div class="row">
        
        <div class="">
            <table class="table">
                <thead>
                <th>Full Name</th>
                <th>Email</th>
                <th>Phone Number</th>
                <th>Address</th>
                <th>Gender</th>
                <th>Status</th>
                </thead>
                <tbody>
                <tr>
                </tr>
                </tbody>
            </table>
        </div>

    </div>
</div>
</body>
</html>

ecom_admin/templates/ecom_admin/view_seller.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>view seller</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    <div class="text-center p-4">
        <h1>VIEW SELLER</h1>
    </div>
<div class="container">
    <div class="row">
        
        <div class="">
            <table class="table">
                <thead>
                <th>Seller Name</th>
                <th>Address</th>
                <th>Phone Number</th>
                <th>Email</th>
                <th>Company Name</th>
                <th>Account Holder Name</th>
                <th>IFSC</th>
                <th>Account Number</th>
                <th>Password</th>
                <th>Status</th>
                </thead>
                <tbody>
                <tr class="table-active">
                    
                </tr>
                </tbody>
            </table>
        </div>

    </div>
</div>
</body>
</html>