common/urls.py
from django.urls import path
from . import views

app_name = 'common'
urlpatterns = [
    path('projecthome', views.project_home, name='projecthome'),
    path('customerlogin', views.customer_login, name='customerlogin'),
    path('sellerlogin', views.seller_login, name='sellerlogin'),
    path('customer_reg', views.customer_registration, name='customer_reg'),
    path('seller_reg', views.seller_registration, name='seller_reg'),                                                                       
    path('email_exist', views.email_exist, name='email_exist'),                                                       
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('common/', include('common.urls')),
    path('customer/', include('customer.urls')),
    path('ecom_admin/', include('ecom_admin.urls')),
    path('seller/', include('seller.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

common/models.py
from django.db import models

# Create your models here.
class Customer(models.Model):
    customer_name = models.CharField(max_length=20)# table fields
    customer_email = models.CharField(max_length=30)
    customer_phone = models.BigIntegerField()
    customer_address = models.CharField(max_length=30)
    customer_gender = models.CharField(max_length=30)
    customer_password = models.CharField(max_length=30)
    customer_image = models.ImageField(upload_to='customer/',default='')

class Seller(models.Model):
    seller_name = models.CharField(max_length=20)
    seller_email = models.CharField(max_length=30)
    seller_phone = models.BigIntegerField()
    seller_address = models.CharField(max_length=100)
    company_name = models.CharField(max_length=20)
    acc_holdername = models.CharField(max_length=20)
    ifsc = models.CharField(max_length=20)
    branch = models.CharField(max_length=20)
    acc_number = models.BigIntegerField()
    seller_username = models.CharField(max_length=20)
    seller_password = models.CharField(max_length=20)
    seller_pic = models.ImageField(upload_to='seller/')
    approved = models.BooleanField(default=False)

common/views.py
from django.shortcuts import render, redirect
from .models import Customer,Seller
import random
from django.core.mail import send_mail
from django.conf import settings
from django.http import JsonResponse

# Create your views here.
def project_home(request):
    return render(request, 'common/project_home.html')

def customer_login(request):
    msg = ''
    if request.method == 'POST':
        customer_email = request.POST['customer_email']
        customer_password = request.POST['customer_password']
        
        try:
            customer = Customer.objects.get(customer_email = customer_email, customer_password = customer_password)
            request.session['customer'] = customer.id
            return redirect('customer:customerhome') 
        except:
            msg = 'Incorrect email-id or password'
    return render(request, 'common/customer_login.html',{'msg':msg})

def seller_login(request):
    msg = ''
    if request.method == 'POST':
        seller_username = request.POST['username']
        seller_password = request.POST['password']

        # select * from seller sellerusername = sellerusername and password = password
        try:
            seller = Seller.objects.get(seller_username = seller_username, seller_password = seller_password)


            # if username and password is correct, we set a session variable with key 'seller'
            # session variable can be accessed throughout the application

            # working of django session:
            # when username and password is correct, we set a session variable with key (here key is 'seller') and
            # unique value for each seller (here value is the primary key of the logged seller)
            # if a seller with primary key 2 logs in,  session key will be 'selle' and value will be 2

            # when we set a session, key and value will be stored in django_session table inside database in encrypted format.
            # and the encrypted key will be send with http response to the client(browser)

            # in the client side(browser), the key received from the server will be stored in the browser storage(cookies)
            # when the user request any page (eg: cart page) from the same browser, the same key stored inside cookies will be
            # sending to the server through http request

            #when the request reaches the server, it wil look for the key stored in cookie to match with django_session thable inside
            # the database to find the corresponding user.


            request.session['seller'] = seller.id 
            return redirect('seller:sellerhome')
        except:
            msg = 'Incorrect username or password' # it calls in the html
    return render(request, 'common/seller_login.html',{'msg':msg})

def customer_registration(request):

    if request.method == 'POST': # works when button clicks
        cst_name = request.POST['cust_name'] #here we get data input in textbox, cust_name is the name of inputbox
        cst_email = request.POST['cust_email']
        cst_phone = request.POST['cust_phone']
        cst_address = request.POST['cust_address']
        cst_gender = request.POST['cust_gender']
        cst_password = request.POST['cust_password']
        cst_image = request.FILES['customer_image']
        # to  insert data into table
        #1. create object of model class, eg: Customer

        new_customer = Customer(customer_name = cst_name, 
         customer_email = cst_email,
         customer_phone = cst_phone,
         customer_address = cst_address,
         customer_gender = cst_gender, 
         customer_password = cst_password,
         customer_image = cst_image)

        # call save() method, here save() method is equivalent to insert into sql query
        new_customer.save()
    return render(request, 'common/customer_reg.html')

def seller_registration(request):
    if request.method == 'POST':
        seller_name = request.POST['seller_name']
        seller_email = request.POST['seller_email']
        seller_phone = request.POST['seller_phone']
        seller_address = request.POST['seller_address']
        company_name = request.POST['company_name']
        seller_acc_holdername = request.POST['acc_holde_name']
        seller_ifsc = request.POST['ifsc']
        seller_branch = request.POST['branch']
        seller_acc_number = request.POST['acc_number']
        seller_image = request.FILES['seller_image']
        seller_username = random.randint(1111,9999)
        seller_password = 'sel-' + seller_name.lower() + str(seller_username)
        message = 'hi, your user name is ' + str(seller_username) + 'and temporary password is ' + seller_password

        send_mail(
            'username and temporary password',
            message,
            settings.EMAIL_HOST_USER,
            [seller_email,],
            fail_silently=False
        )
        new_seller = Seller(seller_name=seller_name,seller_email=seller_email,
            seller_phone=seller_phone,seller_address=seller_address,
            company_name=company_name,acc_holdername=seller_acc_holdername,
            ifsc=seller_ifsc,branch=seller_branch,acc_number=seller_acc_number,
            seller_username=seller_username,seller_password=seller_password,
            seller_pic=seller_image)

        new_seller.save()
    return render(request, 'common/seller_reg.html')

def email_exist(request):
    email = request.POST['email'] # here 'email' is the key inside Json

    status = Customer.objects.filter(customer_email = email).exists()

    return JsonResponse({'status':status}) # the rquest and response both are in Json format.

common/templates/common/common_master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Common Master</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/01741b9219.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">ECOMApp</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Review</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Prime
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <!-- <li class="nav-item">
                <a class="nav-link disabled">Disabled</a>
              </li> -->
              <li class="nav-item">
                <a class="nav-link" href="#">About us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Contact</a>
              </li>
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
            <!-- <button class="btn btn-outline-success" type="submit"><a href="/common/customerlogin">LOGIN</a></button> -->
          </div>
        </div>
      </nav>
      {% block content %}

      
      {% endblock%}
</body>

<footer>
    <div class="row">
        <div class="col">
            <h3>ECOMApp</h3>
            <p>agdjhskhdlsjklskl;<br>dgshdkjlkd<br>jhddkll;sak;l;.</p>
        </div>
        <div class="col">
            <h3>Office</h3>
            <p>ABC Road</p>
            <p>While Field, ABCD</p>
            <p>Kerala, PIN 673501, India</p>
            <p class="email-id">abcd@gmail.com</p>
            <p>+91 - 01234567</p>
        </div>
        <div class="col">
            <h3>Links</h3>
            <ul>
                <li><a href="#">About Us</a></li>
                <li><a href="#">Services</a></li>
                <li><a href="#">Clients</a></li>
                <li><a href="#">Awards</a></li>
                <li><a href="#">Blog</a></li>
            </ul>
        </div>
        <div class="col">
            <h3>Newsletter</h3>
            <form action="">
                <i class="fa-regular fa-envelope"></i>
                <input type="email" placeholder=" Enter your email id" required>
                <button type="submit"><i class="fa-solid fa-arrow-right"></i></button>
            </form>
            <div class="social-icons">
                <i class="fa-brands fa-square-facebook"></i>
                <i class="fa-brands fa-square-twitter"></i>
                <i class="fa-brands fa-square-whatsapp"></i>
                <i class="fa-brands fa-square-instagram"></i>
            </div>
        </div>
    </div>
    <hr>
    <p class="copyright">©ECOMApp Ltd 2022</p>
</footer>
</html>

common/templates/common/customer_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <!-- <link rel="stylesheet" href="{% static 'css/login.css' %}"> -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <style>
    *{
    padding: 0;
    margin: 0;
    box-sizing: border-box;
    }
    body{
        background: rgb(146, 149, 149);
    }
    .row{
        background: white;
        border-radius: 30px;
        box-shadow: 12px 12px 22px grey;
    }
    img{
        border-top-left-radius: 30px;
        border-bottom-left-radius: 30px;
    }
    .btn1{
        border: none;
        outline: none;
        height: 50px;
        width: 100%;
        background-color: black;
        color: white;
        border-radius: 4px;
        font-weight: bold;
    }
    .btn1:hover{
        background: white;
        border: 1px solid;
        color: black;
    }
    </style>
</head>
<body>
    <section class="form my-4 mx-5">
        <div class="container">
            <div class="row no-gutters">
                <div class="col-lg-5">
                    <img src="{% static 'images/log.jpg' %}" class="img" alt="" height="500px" width="500px">
                </div>
                <div class="col-lg-7 px-5 pt-5">
                    <h1 class="font-weight-bold py-3">ECOMApp</h1>
                    <h4>Sign into your account</h4>
                    <form method='POST'>
                        {% csrf_token %}
                        {{msg}}
                        <div class="form-row">
                            <div class="col-lg-7">
                                <input type="email" placeholder="email address" class="form-control my-3" name="customer_email">
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-7">
                                <input type="password" placeholder="*******" class="form-control my-3" name="customer_password">
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-7">
                               <button type="submit" class="btn1 mt-3 mb-5">Login</button>
                            </div>
                        </div>
                        <a href="#">Forgot Password</a>
                        <p>Don't have an account?<a href="/common/customer_reg">Register</a></p>
                    </form>
                </div>
            </div>
        </div>
    </section>
</body>
</html>

common/templates/common/customer_reg.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Customer registration</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.1.js" integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=" crossorigin="anonymous"></script>
    <style>
    *{
    padding: 15px;
    margin: 20px;
    /* box-sizing: border-box; */
    }
    body{
        background: rgb(146, 149, 149);
    }
    </style>
</head>
<body>
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
        <div class="mb-3">
            <label for="exampleInputName" class="form-label">Full Name</label>
            <input type="text" class="form-control" id="exampleInputName" name="cust_name">
          </div>
        <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label">Email address</label>
          <input type="email" class="form-control" id="email" aria-describedby="emailHelp" name="cust_email">
          <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
        </div>
        <div class="mb-3">
            <label for="exampleInputPhone" class="form-label">Pnone</label>
            <input type="number" class="form-control" id="exampleInputPhone" name="cust_phone">
          </div>
        <div class="mb-3">
            <label for="exampleInputAddress" class="form-label">Address</label>
            <textarea id="exampleInputAddress" class="form-control" rows="4" cols="50" name="cust_address"></textarea>
            <!-- <input type="text" class="form-control" id="exampleInputAddress"> -->
          </div>
          <div class="mb-3">
            <label for="" class="form-label">Gender</label><br><br>
                <input type="radio" name="cust_gender" value="Male">Male<br><br>
                <input type="radio" name="cust_gender" value="Female">Female<br><br>
          </div>
        <div class="mb-3">
          <label for="exampleInputPassword1" class="form-label">Password</label>
          <input type="password" class="form-control" id="exampleInputPassword1" name="cust_password">
        </div>
        <div class="mb-3">
          <label for="exampleInputFile" class="form-label">Photo</label>
          <input type="file" class="form-control" id="exampleInputFile" name="customer_image">
        </div>
        
        <!-- <div class="mb-3 form-check">
          <input type="checkbox" class="form-check-input" id="exampleCheck1">
          <label class="form-check-label" for="exampleCheck1">Check me out</label>
        </div> -->
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>

      <script>
        $('#email').change(function(){
          $.ajaxSetup({ // passing csrf_token is ajax request
            headers: {
              "X-CSRFToken": $('[name=csrfmiddlewaretoken]').val()
          }
        })

          $.ajax({
            url:"{% url 'common:email_exist' %}", // url in which ajax call is made
            type:'POST', // method in which data is send
            data:{
              email:$(this).val() // here key is email. this is used for input box
            },
            success:function(response){
                console.log(response.status)
                  alert('Email id already exists')
            }
          })
          })
      </script>
</body>
</html>

common/templates/common/project_home.html
{% extends 'common/common_master.html' %}

{% load static %}

{% block content %}

  <!-- <section class="form my-4 mx-5">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <h4><a href="/common/sellerlogin">SELLER</a></h4>
            </div>
            <div class="col-lg-6">
                <h4><a href="/common/customerlogin">CUSTOMER</a></h4>
            </div>
        </div>
    </div>
</section> -->
<br><br><br><br>
<section class="banner-left bg-olive">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-12 col-lg-6">
                <div class="banner-content">
                    <div style="float:right; background-color:aquamarine; width:700px; height:400px; border-radius:250px;margin-right: -100px;">
                        <a href="/common/sellerlogin"><center><img src="{% static 'images/seller.webp' %}" alt="" style="margin-top:50px;"></center></a>
                    </div>
                </div>
            </div>
            <div class="col-lg-6" style="float: right;color:rgb(18, 99 ,228)">
                <div class="mb-3" style="background-color:aquamarine; width:700px; height:400px; border-radius:250px; margin-left: 100px;">
                    <a href="/common/customerlogin"><center><img src="{% static 'images/customer.jpg' %}" alt="" width="400px" height="280px" style="margin-top:50px;;"></center></a>
                </div>
            </div>
        </div>
    </div>
</section>
<br><br><br><br>
{% endblock %}

common/templates/common/seller_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <!-- <link rel="stylesheet" href="{% static 'css/login.css' %}"> -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <style>
    *{
    padding: 0;
    margin: 0;
    box-sizing: border-box;
    }
    body{
        background: rgb(146, 149, 149);
    }
    .row{
        background: white;
        border-radius: 30px;
        box-shadow: 12px 12px 22px grey;
    }
    img{
        border-top-left-radius: 30px;
        border-bottom-left-radius: 30px;
    }
    .btn1{
        border: none;
        outline: none;
        height: 50px;
        width: 100%;
        background-color: black;
        color: white;
        border-radius: 4px;
        font-weight: bold;
    }
    .btn1:hover{
        background: white;
        border: 1px solid;
        color: black;
    }
    </style>
</head>
<body>
    <section class="form my-4 mx-5">
        <div class="container">
            <div class="row no-gutters">
                <div class="col-lg-5">
                    <img src="{% static 'images/sel.jpeg' %}" class="img" alt="" height="500px" width="500px">
                </div>
                <div class="col-lg-7 px-5 pt-5">
                    <h1 class="font-weight-bold py-3">ECOMApp</h1>
                    <h4>Sign into your account</h4>
                    <form method='POST'>
                        {% csrf_token %}
                        {{msg}}
                        <div class="form-row">
                            <div class="col-lg-7">
                                <input type="text" placeholder="username" class="form-control my-3" name="username">
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-7">
                                <input type="password" placeholder="*******" class="form-control my-3" name="password">
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-7">
                               <button type="submit" class="btn1 mt-3 mb-5">Login</button>
                            </div>
                        </div>
                        <a href="#">Forgot Password</a>
                        <p>Don't have an account?<a href="/common/seller_reg">Register</a></p>
                    </form>
                </div>
            </div>
        </div>
    </section>
</body>
</html>

common/templates/common/seller_reg.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Seller registration</title>
    <!-- <link rel="stylesheet" href="{% static 'css/login.css' %}"> -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

    <style>
      *{
      padding: 2px;
      margin: 30px;
      /* box-sizing: border-box; */
      }
      body{
          background: rgb(167, 244, 244);
      }
      </style>
</head>
<body>
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
        <div class="mb-3">
            <label for="exampleInputName" class="form-label">Seller Name</label>
            <input type="text" class="form-control" id="exampleInputName" name="seller_name">
          </div>
        <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label">Email address</label>
          <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="seller_email">
          <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
        </div>
        <div class="mb-3">
            <label for="exampleInputPhone" class="form-label">Pnone</label>
            <input type="number" class="form-control" id="exampleInputPhone" name="seller_phone">
          </div>
        <div class="mb-3">
            <label for="exampleInputAddress" class="form-label">Address</label>
            <textarea id="exampleInputAddress" class="form-control" name="seller_address" rows="4" cols="50"></textarea>
            <!-- <input type="text" class="form-control" id="exampleInputAddress"> -->
          </div>
        <div class="mb-3">
            <label for="exampleInputCompanyName" class="form-label">Company Name</label>
            <input type="text" class="form-control" id="exampleInputCompanyName" name="company_name">
        </div>
        <div class="mb-3">
            <label for="AccountHolderName" class="form-label">Account holder Name</label>
            <input type="text" class="form-control" id="AccountHolderName" name="acc_holde_name">
        </div>
        <div class="mb-3">
            <label for="exampleInputIfsc" class="form-label">IFSC</label>
            <input type="text" class="form-control" id="exampleInputIfsc" name="ifsc">
        </div>
        <div class="mb-3">
            <label for="exampleInputBranch" class="form-label">Branch</label>
            <input type="text" class="form-control" id="exampleInputBranch" name="branch">
        </div>
        <div class="mb-3">
            <label for="exampleInputAccNumber" class="form-label">Account Number</label>
            <input type="number" class="form-control" id="exampleInputAccNumber" name="acc_number">
          </div>
        
          <div class="mb-3">
            <label for="exampleInputFile" class="form-label">Photo</label>
            <input type="file" class="form-control" id="exampleInputFile" name="seller_image">
          </div>
        
        <!-- <div class="mb-3">
          <label for="exampleInputPassword1" class="form-label">Password</label>
          <input type="password" class="form-control" id="exampleInputPassword1">
        </div> -->
        
        <!-- <div class="mb-3 form-check">
          <input type="checkbox" class="form-check-input" id="exampleCheck1">
          <label class="form-check-label" for="exampleCheck1">Check me out</label>
        </div> -->
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
</body>
</html>